name: Check Status
on: [push, pull_request]

jobs:
  check-status:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1
      - name: pnpm cache
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'


      - name: install
        run: npm ci

      - name: prepublishOnly
        run: npm run prepublishOnly
